 
# Errore: YVALVO_007
    # ERROR
    INSERT INTO <SCH>ERROR (ERROR_ID,  SEVERITY, FW_DATA_OWNER_ID, ENABLE_FORCEABILITY) VALUES ('YVALVO_007', '2', 'THIP_PERS', 'Y');
    # ERROR_NLS
    INSERT INTO <SCH>ERROR_NLS (ERROR_ID, LANGUAGE, TEXT, LONG_TEXT) VALUES ('YVALVO_007', 'it', 'Match Matricola', <LONG_TEXT>'Attenzione, per l''articolo {0} è già stato definito un match con range di matricole che va da {1} a {2}, legare comunque?');
