# Class path : com.thera.thermfw.util.Replacement
# Class name : REPLACEMENT
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it/thera/thip/vendite/documentoVE/DocVenTestataEstratto.js', 'it/valvorobica/thip/vendite/documentoVE/YDocVenTestataEstratto.js', '2', 'N');
 	INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.vendite.documentoVE.web.DocumentoTestataVenditaEstrattoFormActionAdapter', 'it.valvorobica.thip.vendite.documentoVE.web.YDocumentoTestataVenditaEstrattoFormActionAdapter', '0', 'N');
