    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.base.articolo.MicroFamiglia', 'it.valvorobica.thip.base.articolo.YMicroFamiglia', '0', 'Y');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.base.articolo.MicroFamigliaTM', 'it.valvorobica.thip.base.articolo.YMicroFamigliaTM', '0', 'Y');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('MicroFamiglia', 'YMicroFamiglia', '1', 'Y');
