    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.produzione.ordese.OrdineEsecutivo', 'it.valvorobica.thip.produzione.ordese.YOrdineEsecutivo', '0', 'Y');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.produzione.ordese.OrdineEsecutivoTM', 'it.valvorobica.thip.produzione.ordese.YOrdineEsecutivoTM', '0', 'Y');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('OrdineEsecutivo', 'YOrdineEsecutivo', '1', 'Y');
